# version: '3'
# services:
#   nginx:
#     build:
#       context: ./nginx
#       dockerfile: Dockerfile
#     ports:
#       - 4000:4000
#     depends_on:
#       - ledger_server1
#       - ledger_server2
#   ledger_server1:
#     container_name: ledger1_container
#     image: ledger
#     environment:
#       PORT: 4001
#       ENV: development
#       API_ACCESS_KEY: mexu
#       DB_HOST: 192.168.1.64
#       DB_PORT: 3306
#       DB_NAME: ledger1
#       DB_USERNAME: root
#       DB_PASSWORD: ''
#       SERVER_ID: ls1
#       BROKER_1: 192.168.1.64:9092
#       BROKER_2: 192.168.1.64:9093
#     ports:
#       - 4001:4001

#   ledger_server2:
#     container_name: ledger2_container
#     image: ledger
#     environment:
#       PORT: 4001
#       ENV: development
#       API_ACCESS_KEY: mexu
#       DB_HOST: 192.168.1.64
#       DB_PORT: 3306
#       DB_NAME: ledger2
#       DB_USERNAME: root
#       DB_PASSWORD: ''
#       SERVER_ID: ls2
#       BROKER_1: 192.168.1.64:9092
#       BROKER_2: 192.168.1.64:9093
#     ports:
#       - 4002:4001
   

