version: '3'
services:
  zookeeper1:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888

  zookeeper2:
    image: wurstmeister/zookeeper
    ports:
      - 2182:2182
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888

  zookeeper3:
    image: wurstmeister/zookeeper
    ports:
      - 2183:2183
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888

  kafka1:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
      KAFKA_BROKER_ID: 1

  kafka2:
    image: wurstmeister/kafka
    ports:
      - 9093:9093
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
      KAFKA_BROKER_ID: 2

  kafka3:
    image: wurstmeister/kafka
    ports:
      - 9094:9094
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
      KAFKA_BROKER_ID: 3

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 5000:80

  ledger_server1:
    container_name: ledger1_container
    image: ledger
    environment:
      PORT: 4000
      ENV: development
      API_ACCESS_KEY: mexu
      DB_HOST: localhost
      DB_PORT: 3306
      DB_NAME: ledger1
      DB_USERNAME: root
      DB_PASSWORD: ''
      SERVER_ID: s1
      BROKER_1: kafka1:9092
      BROKER_2: kafka2:9093
      BROKER_3: kafka3:9094
    ports:
      - 4000:4000

  ledger_server2:
    container_name: ledger2_container
    image: ledger
    environment:
      PORT: 4000
      ENV: development
      API_ACCESS_KEY: mexu
      DB_HOST: localhost
      DB_PORT: 3306
      DB_NAME: ledger2
      DB_USERNAME: root
      DB_PASSWORD: ''
      SERVER_ID: s2
      BROKER_1: kafka1:9092
      BROKER_2: kafka2:9093
      BROKER_3: kafka3:9094
    ports:
      - 4001:4000

  ledger_server3:
    container_name: ledger3_container
    image: ledger
    environment:
      PORT: 4000
      ENV: development
      API_ACCESS_KEY: mexu
      DB_HOST: localhost
      DB_PORT: 3306
      DB_NAME: ledger3
      DB_USERNAME: root
      DB_PASSWORD: '' 
      SERVER_ID: s3
      BROKER_1: kafka1:9092
      BROKER_2: kafka2:9093
      BROKER_3: kafka3:9094
    ports:
      - 4002:4000
